Migrate to JUnit 5
saucelabs/saucerest-java pull request #121
Opened 2020-10-09 20:44 UTC by valfirst

2020-10-09 21:13 UTC, sceiler requested changes

2020-10-09 21:13 UTC, sceiler commented on src/test/java/com/saucelabs/saucerest/SauceRESTTest.java
> +    void testGetJobsLimit() {
Why are the access modifiers for this and the following tests removed?

2020-10-09 21:13 UTC, sceiler commented on pom.xml
> +                <version>5.7.0</version>
I think this should be extracted into a property under properties.

2020-10-09 21:13 UTC, sceiler commented on pom.xml
> +            <version>2.2</version>
Same as above

2020-10-09 21:13 UTC, sceiler commented on pom.xml
> +                <version>2.22.2</version>
Same as above

2020-10-09 21:16 UTC, sceiler commented on pom.xml
> +            <version>2.2</version>
On hindsight nevermind.

2020-10-09 21:16 UTC, sceiler commented on pom.xml
> +                <version>2.22.2</version>
Nevermind.

2020-10-11 11:35 UTC, valfirst commented on src/test/java/com/saucelabs/saucerest/SauceRESTTest.java
> +    void testGetJobsLimit() {
JUnit5 doesn't require `public` access modifier anymore and default access modifier improves readability:
https://rules.sonarsource.com/java/tag/junit/RSPEC-5786

2020-10-12 13:40 UTC, sceiler commented on src/test/java/com/saucelabs/saucerest/SauceRESTTest.java
> +    void testGetJobsLimit() {
Thx, good to know.

2020-10-12 13:40 UTC, sceiler approved these changes

2020-10-12 13:41 UTC, merged