Refactor assets fetching, add missing asset endpoints and clean up code
saucelabs/saucerest-java pull request #130
Opened 2020-10-23 12:16 UTC by sceiler

## Description

Overhaul asset fetching/download/saving.
Add missing endpoints for assets.
Add retry mechanism to download when assets are not ready yet.

This fixes #58, #59, #60, 
## Motivation and Context

Open issues requesting it. General desire to improve this library as it is also used and was mentioned during POCs.
## How Has This Been Tested?

New unit tests, adapted unit tests, used locally in E2E tests.
## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (change which improves current code base; please describe the change)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Screenshots (if appropriate):

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/saucelabs/saucerest-java/blob/master/CONTRUBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All new and existing tests passed locally
- [x] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2020-10-25 08:47 UTC, diemol requested changes
Thank you for this PR! A few comments :)

In general, it is preferable to have one PR per each issue fixed, as this would simplify reviewing.

2020-10-25 08:47 UTC, diemol commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +    }
There is some code duplicated here, probably `downloadDeviceLog(String jobId, String location, boolean isEmulator)` should call `downloadDeviceLog(String jobId, String location, String filename, boolean isEmulator)` with the default `filename` parameter.

2020-10-25 08:47 UTC, diemol commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +     * @param isEmulator to determine what device log to download
I am not sure if this already existed and it looks like a new addition due to the refactoring. But `isEmulator` is probably limiting the scope. I know we only have for now emulators and simulators through the API, but we could have an enum that contains emulators, simulators, and (for the future) real devices.

2020-10-25 08:47 UTC, diemol commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +    public void downloadDeviceLogOrThrow(String jobId, String location, boolean isEmulator) throws SauceException.NotAuthorized, IOException {
Do you know why we have these `OrThrow` methods? They are giving implementation details about the API wrapper. I mean, we should always throw exceptions that the client should handle, and not offer these methods that make them think if they should handle that or not.

2020-10-25 08:47 UTC, diemol commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +    public boolean downloadScreenshots(String jobId, String location, String filename) {
Some little code duplication with `downloadScreenshots(String jobId, String location)`

2020-10-25 08:47 UTC, diemol commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        URL restEndpoint = this.buildURL(username + "/jobs/" + jobId + "/assets/screenshots.zip");
Some more code duplication with `downloadScreenshotsOrThrow(String jobId, String location, String filename)`

2020-10-25 08:47 UTC, diemol commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +     * Downloads the Selenium/Appium server log for a Sauce Labs job to the filesystem.  The file will be stored in a
We are now having more automation tools supported in our platform (Puppeteer, etc.). Probably leaving the generic `log` term is better.

2020-10-25 08:47 UTC, diemol commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +    public boolean downloadServerLog(String jobId, String location) {
We should not change the methods name as it could potentially break the client's code when they want to upgrade. We should deprecate, have the method deprecated for one release, and then delete.

2020-10-25 08:47 UTC, diemol commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +    public boolean downloadServerLog(String jobId, String location, String fileName) {
We should not change the methods name as it could potentially break the client's code when they want to upgrade. We should deprecate, have the method deprecated for one release, and then delete.

2020-10-25 08:47 UTC, diemol commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +    public boolean downloadAutomatorLog(String jobId, String location) {
We should not change the methods name as it could potentially break the client's code when they want to upgrade. We should deprecate, have the method deprecated for one release, and then delete.

2020-10-25 08:47 UTC, diemol commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +            .withMaxDuration(Duration.ofSeconds(15))
Should we leave these values to be configurable via parameters and having also some defaults?

2020-10-25 08:47 UTC, diemol commented on src/main/java/com/saucelabs/saucerest/AutomationBackend.java
> +public enum AutomationBackend {
This is a good idea since we now have more automation backends.

Should we add the backends for Live Testing, Espresso, XCUITests, and others already? Or wait until someone needs them?

2020-10-25 10:08 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +    public void downloadDeviceLogOrThrow(String jobId, String location, boolean isEmulator) throws SauceException.NotAuthorized, IOException {
I don't know why we have `OrThrow`and the others return a `boolean`. In this case I just went with the rest of the code. If I understand you correctly, I agree with you that the method name shouldn't include `OrThrow` and instead always throw in case of an error and otherwise return `true`. I can make that change in all methods in another PR.

2020-10-25 10:37 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +            .withMaxDuration(Duration.ofSeconds(15))
That is a good point. What is your experience though with users possibly hammering our endpoints because of misconfiguring retry? Though in this case I would expect our service to handle that. Another point would be tests running too long. I guess most of that could be mitigated using some default values...

2020-10-25 10:41 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/AutomationBackend.java
> +public enum AutomationBackend {
I don't know if they are shown in the response/part of the meta data. I looked through some and it always was either appium or webdriver. Too bad we don't have a proper API spec to refer to. :(
I would be happy to add all of them if I know the values they would take. Do you know?

2020-10-25 17:18 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceException.java
> +        public NotAuthorized() { }
Fix with 6b4b90b

2020-10-25 17:23 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        } else if (automationBackend.equals(AutomationBackend.WEBDRIVER.label)) {
Done with c530aac

2020-10-25 17:28 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        jsonObject.remove("video.mp4");
```
{
  "video.mp4": "video.mp4",
  "sauce-log": "log.json",
  "video": "video.mp4",
  "selenium-log": "selenium-server.log",
  "screenshots": [
    "0000screenshot.png",
    "0001screenshot.png",
    "0002screenshot.png",
    "0003screenshot.png",
    "0004screenshot.png",
    "0005screenshot.png"
  ]
}
```
This is an example JSON response. It has `video.mp4` and `video`. The former was added to deprecate .flv videos which were in the latter. At some point .flv was removed completely and now both keys point to the same video as we don't have mp4 anymore. Product is aware of it but meanwhile removing the key should help avoid confusion but also to prevent downloading the same video twice.

2020-10-25 17:49 UTC, enriquegh commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +    public void downloadDeviceLogOrThrow(String jobId, String location, boolean isEmulator) throws SauceException.NotAuthorized, IOException {
Some context on orThrow methods:

https://github.com/saucelabs/saucerest-java/pull/90
https://github.com/saucelabs/saucerest-java/issues/107

If I remember correctly before download could happen and the exception would be swallowed without a warning. 
Dylan changed this so a set of methods would throw the exception if needed and other would return a boolean. 

Did I get that right @DylanLacey?

2020-10-25 17:57 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +    public boolean downloadServerLog(String jobId, String location) {
Ops you are totally right. Restored with ee18fb0

2020-10-25 17:57 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +    public boolean downloadAutomatorLog(String jobId, String location) {
Ops you are totally right. Restored with ee18fb0

2020-10-25 17:57 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +    public boolean downloadServerLog(String jobId, String location, String fileName) {
Ops you are totally right. Restored with ee18fb0

2020-10-25 18:04 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +     * @param isEmulator to determine what device log to download
My problem here was that I don't know the future and roadmap of this library. At least it is written on the README that this library only covers VDC not RDC, for which we would have to rewrite some stuff anyway as the RDC API is differently built. 

Maybe it is better to split this up into `downloadEmulatorLog()` and `downloadSimulatorLog()`?

2020-10-25 18:14 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +    }
Technically you are right however `getDefaultFileName()` and the whole filename algorithm is designed to need `restEndpoint` to determine the filename. When you compare it the other methods it always the same scheme of defining the `restEndpoint` object and then calling `saveFile()`. This comment of yours actually encourages me to split this up into 2 separate methods, one for emulator and one for simulator. That would be more consistent with the rest of the code.

2020-10-25 18:31 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +    public boolean downloadScreenshots(String jobId, String location, String filename) {
Again you are right. :)
My caveat here is that we do it consistent all over the code. Meaning, we could call one of the `downloadX(jobId, location, filename)´ methods and just give the filename from the endpoint as parameter. I think we have this issue because we added the ability to overwrite the default filename and as part of this change should have also changed this now code duplication. Well, we (read I) overlooked that when doing the code review for the filename change (I think it was me).

Having said that it is a good point and I will make this change. Thanks for pointing it out!

2020-10-25 19:02 UTC, diemol commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        jsonObject.remove("video.mp4");
👍 
I think a small comment would help future developers to understand that line of code :)

2020-10-26 12:55 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +    public boolean downloadScreenshots(String jobId, String location, String filename) {
Done with 408edc0

2020-10-26 19:54 UTC, valfirst requested changes

2020-10-26 19:54 UTC, valfirst commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        return null;
```java
return Stream.of(AutomationBackend.values())
             .filter(backend -> backend.label.equalsIgnoreCase(automationBackend))
             .findFirst()
             .orElse(null);
```

2020-10-26 19:54 UTC, valfirst commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        }
```java
String filename = isEmulator ? "logcat.log" : "ios-syslog.log";
```

2020-10-26 19:54 UTC, valfirst commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        }
```java
URL restEndpoint = buildURL(
            username + "/jobs/" + jobId + "/assets/" + (isEmulator ? "logcat" : "ios-syslog") + ".log");
```

2020-10-26 19:54 UTC, valfirst commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        }
```java
String filename = isEmulator ? "logcat.log" : "ios-syslog.log";
```

2020-10-26 19:54 UTC, valfirst commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        }
```java
URL restEndpoint = buildURL(
            username + "/jobs/" + jobId + "/assets/" + (isEmulator ? "logcat" : "ios-syslog") + ".log");
```

2020-10-26 19:54 UTC, valfirst commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +            } else if (throwable instanceof FileNotFoundException) {
`FileNotFoundException` extends `IOException` so this branch is unreachable

2020-10-26 19:54 UTC, valfirst commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +                String errorStream = IOUtils.toString(connection.getErrorStream());
Charset should be specified explicitly

2020-10-26 19:54 UTC, valfirst commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        File targetFile = new File(location, fileName.replaceAll("\\/", "_"));
`fileName.replaceAll("\\/", "_")` -> `fileName.replace('/', '_')`

2020-10-26 19:54 UTC, valfirst commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        System.out.println("Saving " + jobAndAsset + " as " + targetFile);
Logger should be used instead of `System.out`

2020-10-26 19:54 UTC, valfirst commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +            System.out.println("Saving " + jobAndAsset + " as " + targetFile);
Logger should be used instead of `System.out`

2020-10-27 09:52 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        jsonObject.remove("video.mp4");
Done with 5b8d541

2020-10-27 20:19 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +            .withMaxDuration(Duration.ofSeconds(15))
Done with e1fd37c

2020-10-27 20:58 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +            System.out.println("Saving " + jobAndAsset + " as " + targetFile);
Thanks, done with a2d3eb2

2020-10-27 20:59 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        System.out.println("Saving " + jobAndAsset + " as " + targetFile);
Thanks, done with a2d3eb2

2020-10-27 20:59 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        File targetFile = new File(location, fileName.replaceAll("\\/", "_"));
Thanks, done with a2d3eb2

2020-10-27 21:04 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +     * Downloads the Selenium/Appium server log for a Sauce Labs job to the filesystem.  The file will be stored in a
Done with 6a6f734

2020-10-27 21:04 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        }
Thanks, done with a2d3eb2

2020-10-27 21:05 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        }
Done with a2d3eb2

2020-10-27 21:05 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        }
Done with a2d3eb2

2020-10-27 21:05 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        }
Done with a2d3eb2

2020-10-27 21:06 UTC, sceiler commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +        return null;
Done with a2d3eb2

2020-10-28 19:16 UTC, diemol commented on src/main/java/com/saucelabs/saucerest/AutomationBackend.java
> +public enum AutomationBackend {
No, I don't.
Probably we need to wait until the use case shows up.

2020-10-28 19:18 UTC, diemol commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +     * @param isEmulator to determine what device log to download
I am not sure if there is a roadmap, but if we have an enum, we could cover the potential use case where logs from RDC devices can be downloaded.
A boolean is only giving us two options.

2020-10-28 19:21 UTC, diemol commented on src/main/java/com/saucelabs/saucerest/SauceREST.java
> +    public void downloadDeviceLogOrThrow(String jobId, String location, boolean isEmulator) throws SauceException.NotAuthorized, IOException {
I don't think that looks good, mentioning that a method throws in its name is not ideal. We should deprecate these methods and always throw those exceptions, the client should manage them.
But doing that is not in the scope of this PR, so I am ok with it (for now)

2020-10-28 19:21 UTC, diemol approved these changes
Thank you, @sceiler!

2020-10-28 19:32 UTC, merged