Add release workflow.
saucelabs/saucerest-java pull request #210
Opened 2021-12-09 02:21 UTC by DylanLacey

## Description
New release workflow that should _actually_ work.

Requires some secret setup:

1. MAVEN_USERNAME
2. MAVEN_CENTRAL_PASSWORD

Release credentials for releasing user (Suggest we create a Sauce user for this)

3. GPG_PRIVATE_KEY
4. GPG_PASSPHRASE

GPG Credentials for signing release.  Again, suggest we create Sauce-specific creds.

To release, trigger the workflow manually and indicate what kind of release you wish to make.

## Motivation and Context
This allows us to release directly to Maven Central from Github

## How Has This Been Tested?
I've tested this action in my own fork (without performing a release) as well as performing releases with this pom setup on my local machine.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (change which improves current code base; please describe the change)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x ] Documentation Update (if none of the other choices apply)

## Checklist

- [ x ] I have read the [CONTRIBUTING](https://github.com/saucelabs/saucerest-java/blob/master/CONTRUBUTING.md) doc
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] All new and existing tests passed locally
- [ x ] I have added necessary documentation (if appropriate)

## Further comments

We'll need to create the appropriate Maven Central user and GPG certificate for release.

I suggest we also include the GPG Public Key in the documentation so users can verify if concerned.

2021-12-15 09:47 UTC, valfirst requested changes

2021-12-15 09:47 UTC, valfirst commented on .github/workflows/release.yml
>        - name: Set up JDK 1.8
the name doesn't match to the actual used java version

2021-12-15 09:47 UTC, valfirst commented on pom.xml
> +        <java.version>17</java.version>
isn't it too early?

2022-03-20 01:20 UTC, sceiler commented
Closing this PR. Based on Dylans idea here I created a new workflow to do this.

2022-03-20 01:20 UTC, closed without merging