Improve and clean up tests
saucelabs/saucerest-java pull request #313
Opened 2023-01-19 10:43 UTC by valfirst

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (change which improves current code base; please describe the change)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/saucelabs/saucerest-java/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] All new and existing tests passed locally
- [ ] I have added necessary documentation (if appropriate)

2023-01-19 15:28 UTC, sceiler requested changes

2023-01-19 15:28 UTC, sceiler commented on src/test/java/com/saucelabs/saucerest/integration/JobTest.java
> +        );
What does this change and why is it done?

2023-01-19 15:28 UTC, sceiler commented on src/test/java/com/saucelabs/saucerest/Helper.java
> -}
Why remove this?

2023-01-19 15:28 UTC, sceiler commented on src/test/java/com/saucelabs/saucerest/integration/JobTest.java
> +        );
What does this change and why do it?

2023-01-19 15:28 UTC, sceiler commented on src/test/java/com/saucelabs/saucerest/unit/SauceRESTTest.java
>          sauceREST.getBuildsByName(jobSource, "Build name#1", 2);
What is the benefit of using IOUtils.toInputStream vs. ByteArrayInputStream? Why make this change?
Why change from HashMap as type to Map instead? What is the benefit of this change?

2023-01-22 22:35 UTC, valfirst commented on src/test/java/com/saucelabs/saucerest/integration/JobTest.java
> +        );
Lambda expression with code block body was replaced with expression-style body: the result  is shorter and more clear.

2023-01-22 22:36 UTC, valfirst commented on src/test/java/com/saucelabs/saucerest/Helper.java
> -}
It's not used

2023-01-22 22:36 UTC, valfirst commented on src/test/java/com/saucelabs/saucerest/integration/JobTest.java
> +        );
Lambda expression with code block body was replaced with expression-style body: the result is shorter and more clear.

2023-01-22 22:39 UTC, valfirst commented on src/test/java/com/saucelabs/saucerest/unit/SauceRESTTest.java
>          sauceREST.getBuildsByName(jobSource, "Build name#1", 2);
> What is the benefit of using IOUtils.toInputStream vs. ByteArrayInputStream? Why make this change?

Les boilerplate code, more concise statements.

> Why change from HashMap as type to Map instead? What is the benefit of this change?

https://www.baeldung.com/cs/program-to-interface

2023-02-03 16:35 UTC, sceiler requested changes

2023-02-03 16:35 UTC, sceiler commented on src/test/java/com/saucelabs/saucerest/integration/SauceConnectTest.java
> -            Assertions.assertNotNull(jobsForATunnel.jobsRunning);
It is better to treat and test every single endpoint as isolated as possible because given the nature of this project the int tests can be considered as unit tests to some degree.

2023-02-03 16:35 UTC, sceiler commented on src/test/java/com/saucelabs/saucerest/integration/StorageTest.java
> +            "My App File Description");
Please revert line wrapping.

2023-02-03 16:35 UTC, sceiler commented on src/test/java/com/saucelabs/saucerest/Helper.java
> -}
It is a helper and might be required going forward. Please revert.

2023-02-03 16:35 UTC, sceiler commented on src/test/java/com/saucelabs/saucerest/integration/StorageTest.java
> +            "My App File Description");
Please revert line wrapping.

2023-05-16 00:05 UTC, closed without merging

2023-05-16 00:05 UTC, sceiler commented
Closing as outdated and stale.